# Browser Configuration
browser=chrome
headless=false
browser.timeout=10

# URLs
internet.url=https://the-internet.herokuapp.com
api.base.url=https://reqres.in

# Test Environment
environment=dev

# Screenshots
screenshot.on.failure=true
screenshot.folder=target/screenshots

# Waits
implicit.wait=10
explicit.wait=15
page.load.timeout=30
